-- Services
INSERT INTO services (title, description, icon, link) VALUES 
('Hemp & CBD SEO Services', 'Industry-specific keyword research with semantic clustering and compliance-first content strategy. We understand the nuances of hemp SEO and create content that ranks while staying fully compliant with Google guidelines and state regulations. Our approach includes entity-based optimization, topical authority building, and strategic internal linking.', 'ri-search-line', 'hemp_seo_service.php'),
('Vape SEO Services', 'Specialized SEO for vape shops and vape product brands. We build algorithm-resistant rankings with age-gate optimization, device and e-liquid product page SEO, SERP volatility monitoring, and brand authority building through compliant content strategies that drive consistent traffic both locally and nationally.', 'ri-mist-line', 'vape_seo_service.php'),
('Local SEO for Dispensaries', 'Google Business Profile optimization, 500+ local citations, and location-specific landing pages. We help dispensaries dominate local search results with geo-targeted content, review management, local link building, and NAP consistency across all platforms. Perfect for multi-location cannabis businesses.', 'ri-map-pin-line', '#local-seo'),
('Google Ads for CBD (Compliant)', 'Compliant Google Ads campaigns that actually work for CBD and hemp products. We navigate the complex advertising restrictions with white-hat strategies, alternative keyword targeting, and landing page optimization that passes Google review. Achieve profitable ROAS while staying within platform guidelines.', 'ri-advertisement-line', '#google-ads'),
('Technical SEO & CRO', 'Comprehensive technical audits, Core Web Vitals optimization, and conversion rate optimization. We fix crawl errors, improve site architecture, implement structured data, and optimize page speed. Our CRO strategies include A/B testing, heat mapping analysis, and user experience improvements that increase conversions.', 'ri-line-chart-line', '#technical-seo'),
('Link Building for Hemp Brands', 'White-hat link acquisition in restricted niches with high-authority backlinks from relevant hemp, wellness, and lifestyle publications. We build sustainable link profiles through content partnerships, digital PR, and relationship building with industry influencers and authoritative websites in the cannabis space.', 'ri-links-line', '#link-building');

-- Case Studies
INSERT INTO case_studies (title, category, challenge, solution, image_path, metric1_value, metric1_label, metric2_value, metric2_label, metric3_value, metric3_label) VALUES 
('Premium CBD Brand', 'CBD Ecommerce', 'New CBD ecommerce store struggling to rank for competitive keywords and generate organic traffic', 'Implemented comprehensive Hemp SEO strategy including technical optimization, content marketing, and strategic link building', './Hemp%20SEO%20Agency%20_%20CBD,%20Cannabis%20&%20Vape%20SEO%20Services%20_%20HempSuccess_files/search-image(12)', '385%', 'Organic Traffic Increase', '12x', 'Keyword Rankings', '$250K', 'Monthly Revenue'),
('Multi-Location Dispensary', 'Cannabis Retail', 'Dispensary chain needed to dominate local search across 8 locations in competitive markets', 'Developed location-specific landing pages, optimized Google Business Profiles, and built local citations', './Hemp%20SEO%20Agency%20_%20CBD,%20Cannabis%20&%20Vape%20SEO%20Services%20_%20HempSuccess_files/search-image(13)', '520%', 'Local Search Visibility', '#1', 'Rankings in 6 Cities', '180%', 'Foot Traffic Growth'),
('Hemp Wellness Brand', 'Hemp Products', 'Established hemp brand losing market share to competitors with better online visibility', 'Rebuilt content strategy with entity-based SEO, improved technical performance, and acquired high-authority backlinks', './Hemp%20SEO%20Agency%20_%20CBD,%20Cannabis%20&%20Vape%20SEO%20Services%20_%20HempSuccess_files/search-image(14)', '290%', 'Organic Revenue', '450+', 'Page 1 Rankings', '4.2x', 'ROAS');

-- Testimonials
INSERT INTO testimonials (client_name, position, company, content, rating, image_path) VALUES 
('Sarah Mitchell', 'CEO', 'GreenLeaf CBD', '"Working with this Hemp SEO Agency transformed our business. We went from page 3 to dominating page 1 for our most important keywords. Our organic traffic increased 385% in just 6 months, and revenue has tripled. They truly understand the hemp industry and compliance requirements."', 5, './Hemp%20SEO%20Agency%20_%20CBD,%20Cannabis%20&%20Vape%20SEO%20Services%20_%20HempSuccess_files/search-image(15)'),
('Michael Chen', 'Owner', 'Urban Dispensary', '"As a multi-location dispensary, local SEO was critical for us. This team delivered beyond expectations. We now rank #1 in all our target cities, and foot traffic has increased dramatically. Their understanding of cannabis regulations and local search is unmatched."', 5, './Hemp%20SEO%20Agency%20_%20CBD,%20Cannabis%20&%20Vape%20SEO%20Services%20_%20HempSuccess_files/search-image(16)'),
('Jennifer Rodriguez', 'Marketing Director', 'Hemp Wellness Co', '"Finally, an SEO agency that gets the hemp industry! Their strategic approach to content and link building has positioned us as an authority in our niche. We have seen consistent month-over-month growth in rankings, traffic, and most importantly, revenue."', 5, './Hemp%20SEO%20Agency%20_%20CBD,%20Cannabis%20&%20Vape%20SEO%20Services%20_%20HempSuccess_files/search-image(17)'),
('David Thompson', 'Founder', 'Vape Nation', '"The results speak for themselves. Our vape shop went from struggling to find customers online to being the top result for dozens of high-value keywords. The Hemp SEO Agency team is responsive, transparent, and delivers real ROI."', 5, './Hemp%20SEO%20Agency%20_%20CBD,%20Cannabis%20&%20Vape%20SEO%20Services%20_%20HempSuccess_files/search-image(18)'),
('Amanda Foster', 'Owner', 'Pure CBD Store', '"I have worked with several SEO agencies before, but none understood the unique challenges of CBD ecommerce like this team. They optimized our entire site, created amazing content, and built quality backlinks. Our sales have increased 290% year-over-year."', 5, './Hemp%20SEO%20Agency%20_%20CBD,%20Cannabis%20&%20Vape%20SEO%20Services%20_%20HempSuccess_files/search-image(19)'),
('Robert Martinez', 'Director', 'Cannabis Collective', '"Outstanding service and results. This Hemp SEO Agency helped us navigate the complex world of cannabis marketing with compliant strategies that actually work. We have seen tremendous growth in organic visibility and customer acquisition."', 5, './Hemp%20SEO%20Agency%20_%20CBD,%20Cannabis%20&%20Vape%20SEO%20Services%20_%20HempSuccess_files/search-image(20)');

-- Brands
INSERT INTO brands (name, image_path) VALUES 
('Hemp Brand 1', './Hemp%20SEO%20Agency%20_%20CBD,%20Cannabis%20&%20Vape%20SEO%20Services%20_%20HempSuccess_files/search-image(2)'),
('CBD Store 2', './Hemp%20SEO%20Agency%20_%20CBD,%20Cannabis%20&%20Vape%20SEO%20Services%20_%20HempSuccess_files/search-image(3)'),
('Vape Brand 3', './Hemp%20SEO%20Agency%20_%20CBD,%20Cannabis%20&%20Vape%20SEO%20Services%20_%20HempSuccess_files/search-image(4)'),
('Cannabis Co 4', './Hemp%20SEO%20Agency%20_%20CBD,%20Cannabis%20&%20Vape%20SEO%20Services%20_%20HempSuccess_files/search-image(5)'),
('Hemp Products 5', './Hemp%20SEO%20Agency%20_%20CBD,%20Cannabis%20&%20Vape%20SEO%20Services%20_%20HempSuccess_files/search-image(6)'),
('CBD Wellness 6', './Hemp%20SEO%20Agency%20_%20CBD,%20Cannabis%20&%20Vape%20SEO%20Services%20_%20HempSuccess_files/search-image(7)');
